// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLTuWWVhCWGuk0aPWYgWih2niMppAjwrU',
    appId: '1:1025392045761:web:dbaf0180621855bc386e40',
    messagingSenderId: '1025392045761',
    projectId: 'cashflow-ae88c',
    authDomain: 'cashflow-ae88c.firebaseapp.com',
    storageBucket: 'cashflow-ae88c.appspot.com',
    measurementId: 'G-HXB4BMGVD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdbQegNmDGVZJaWcANzQQDE7ASwkAPOI4',
    appId: '1:1025392045761:android:79eb802fcd985907386e40',
    messagingSenderId: '1025392045761',
    projectId: 'cashflow-ae88c',
    storageBucket: 'cashflow-ae88c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQWJ7VKfgfBelUzjaYBM51EUTQLa9TyFM',
    appId: '1:1025392045761:ios:5d801a26babb8f4e386e40',
    messagingSenderId: '1025392045761',
    projectId: 'cashflow-ae88c',
    storageBucket: 'cashflow-ae88c.appspot.com',
    iosClientId: '1025392045761-fd43ov51vlf0qcs1c2rkuc2jmgfo5ael.apps.googleusercontent.com',
    iosBundleId: 'com.example.budget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQWJ7VKfgfBelUzjaYBM51EUTQLa9TyFM',
    appId: '1:1025392045761:ios:5d801a26babb8f4e386e40',
    messagingSenderId: '1025392045761',
    projectId: 'cashflow-ae88c',
    storageBucket: 'cashflow-ae88c.appspot.com',
    iosClientId: '1025392045761-fd43ov51vlf0qcs1c2rkuc2jmgfo5ael.apps.googleusercontent.com',
    iosBundleId: 'com.example.budget',
  );
}
